# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-19 15:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipam', '0004_ipam_vlangroup_uniqueness'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipaddress',
            name='hostname',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
