# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-20 09:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipam', '0005_ipaddress_hostname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipaddress',
            name='hostname',
            field=models.CharField(blank=True, max_length=100, verbose_name=b'Host Name'),
        ),
    ]
