# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-22 09:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipam', '0006_auto_20160720_0941'),
    ]

    operations = [
        migrations.AddField(
            model_name='prefix',
            name='soa_contact',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='prefix',
            name='soa_expire',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prefix',
            name='soa_minimum',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prefix',
            name='soa_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='prefix',
            name='soa_refresh',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prefix',
            name='soa_retry',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prefix',
            name='soa_serial',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='prefix',
            name='ttl',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
