# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-27 13:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipam', '0007_auto_20160722_0958'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ipaddress',
            name='hostname',
        ),
        migrations.AddField(
            model_name='ipaddress',
            name='ptr',
            field=models.CharField(blank=True, max_length=100, verbose_name=b'PTR'),
        ),
    ]
