# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-28 08:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipam', '0008_auto_20160727_1307'),
    ]

    operations = [
        migrations.AddField(
            model_name='prefix',
            name='bind_changed',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='prefix',
            name='soa_serial',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
