# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-03 09:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ipam', '0007_prefix_ipaddress_add_tenant'),
        ('ipam', '0009_auto_20160728_0854'),
    ]

    operations = [
    ]
