# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-18 14:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipam', '0010_merge'),
    ]

    operations = [
        migrations.AddField(
            model_name='prefix',
            name='extra_conf',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
