# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-21 10:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dns', '0002_auto_20160719_1058'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='record',
            options={'ordering': ['category']},
        ),
        migrations.AddField(
            model_name='record',
            name='category',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='record',
            name='description',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='zone',
            name='description',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
