# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-22 08:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dns', '0003_auto_20160721_1059'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='record',
            options={'ordering': ['name']},
        ),
        migrations.RemoveField(
            model_name='record',
            name='category',
        ),
        migrations.AlterField(
            model_name='record',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='records', to='ipam.IPAddress'),
        ),
    ]
