# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-28 08:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dns', '0004_auto_20160722_0820'),
    ]

    operations = [
        migrations.AddField(
            model_name='zone',
            name='bind_changed',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='zone',
            name='soa_serial',
            field=models.CharField(max_length=10),
        ),
    ]
