# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-16 08:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenancy', '0002_tenant_group_optional'),
    ]

    operations = [
        migrations.CreateModel(
            name='ASN',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('asn', models.IntegerField(unique=True)),
                ('as_name', models.CharField(blank=True, max_length=100)),
                ('as_set4', models.CharField(blank=True, max_length=100)),
                ('as_set6', models.CharField(blank=True, max_length=100)),
                ('lock_as_set', models.BooleanField(default=False)),
                ('prefixes4', models.TextField(blank=True)),
                ('prefixes6', models.TextField(blank=True)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tenancy.Tenant')),
            ],
            options={
                'ordering': ['asn'],
            },
        ),
    ]
